kind: pipeline
name: default

steps:
  - name: build
    image: node:12.16.0
    commands:
      - mv ./docs /website
    volumes:
      - name: vol
        path: /website
  - name: preview
    image: jacie/drone-aliyun-oss
    environment:
      ALIYUN_ACCESS_KEY_ID:
        from_secret: ACCESS_KEY_ID
      ALIYUN_SECRET_ACCESS_KEY:
        from_secret: ACCESS_KEY_SECRET
      PLUGIN_SOURCE: /website/docs
      ALIYUN_BUCKET: oss://docs-rancher2-preview
      ALIYUN_ENDPOINT: oss-cn-hangzhou.aliyuncs.com
    commands:
      - "aliyun-oss"
    volumes:
      - name: vol
        path: /website
    when:
      ref:
        include:
          - "refs/heads/preview"
      event:
        - push
  - name: production
    image: guoxudongdocker/drone-oss
    settings:
      dist: /website/build
      path: docs-rancher2-production/
      endpoint: oss-cn-hangzhou.aliyuncs.com
      access_key_id:
        from_secret: ACCESS_KEY_ID
      access_key_secret:
        from_secret: ACCESS_KEY_SECRET
    volumes:
      - name: vol
        path: /website
    when:
      ref:
        include:
          - "refs/heads/master"
      event:
        - push

volumes:
  - name: vol
    temp: {}
