kind: pipeline
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - name: vol
        path: /build
  - name: oss
    image: alpine:3.8
    volumes:
      - name: vol
        path: /build
    commands:
      - ls /build

volumes:
  - name: vol
    temp: {}
