kind: pipeline
name: default

steps:
  - name: build
    image: node:12.16.0
    commands:
      - yarn install
      - yarn build
      - mv ./build /website
    volumes:
      - name: vol
        path: /website
  - name: oss
    image: alpine:3.8
    volumes:
      - name: vol
        path: /website
    commands:
      - ls /website
      - ls /website/build

volumes:
  - name: vol
    temp: {}
