kind: pipeline
name: default

steps:
  - name: build
    image: node:12.16.0
    commands:
      - node -v
      - touch /build/xxx
      - pwd
    volumes:
      - name: vol
        path: /build
  - name: oss
    image: alpine:3.8
    volumes:
      - name: vol
        path: /build
    commands:
      - ls /build

volumes:
  - name: vol
    temp: {}
