name: CI Build
on:
  pull_request:
  push:
    tags-ignore: [ '**' ]
    branches: [ '**', '!preview', '!master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Dependencies
        run: |
          npm install
      - name: Build website
        run: |
          npm run build
